package br.edu.unijui.gui;

import br.edu.unijui.pcn.logic.DBManager;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpressionException;
import javax.xml.xpath.XPathFactory;
import org.w3c.dom.DOMException;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.xml.sax.SAXException;

/**
 * Interface implementada parcialmente pelo professor. Siga as instruções da
 * avaliação para construir seu programa completo.
 *
 * @author Rafael Zancan Frantz
 */
public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jpMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpDatabaseConnection = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hostName = new javax.swing.JTextField();
        instance = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        port = new javax.swing.JTextField();
        jbLoadXML = new javax.swing.JButton();
        jpLoadData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbInputFileButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        totalRegisters = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numberCities = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numberStates = new javax.swing.JTextField();
        jbRunSystem = new javax.swing.JButton();
        jtfNumberThree = new javax.swing.JLabel();
        jtfNumberOne = new javax.swing.JLabel();
        jpFindIsolationIndex = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        highestIsolationIndex = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lowestIsolationIndex = new javax.swing.JTextField();
        jbFindIsolationIndex = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jcbWhereToFind = new javax.swing.JComboBox<>();
        jtfNumberTwo1 = new javax.swing.JLabel();
        jpXMLTransformer = new javax.swing.JPanel();
        xmlOutputFileName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jbExport = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();
        jtfNumberFour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("COVID-19 Isolation Index System");

        jpMain.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("COVID-19 Isolation Index System");

        jpDatabaseConnection.setBorder(javax.swing.BorderFactory.createTitledBorder("Database Connection Settings"));

        jLabel6.setText("Host name:");

        jLabel7.setText("Username:");

        jLabel8.setText("Password:");

        jLabel9.setText("Instance:");

        hostName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostNameActionPerformed(evt);
            }
        });

        jLabel10.setText("Port:");

        port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portActionPerformed(evt);
            }
        });

        jbLoadXML.setText("Load XML Conf");
        jbLoadXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoadXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDatabaseConnectionLayout = new javax.swing.GroupLayout(jpDatabaseConnection);
        jpDatabaseConnection.setLayout(jpDatabaseConnectionLayout);
        jpDatabaseConnectionLayout.setHorizontalGroup(
            jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hostName)
                    .addComponent(instance)
                    .addComponent(username)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatabaseConnectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLoadXML)
                .addGap(148, 148, 148))
        );
        jpDatabaseConnectionLayout.setVerticalGroup(
            jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatabaseConnectionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatabaseConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(instance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jbLoadXML)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpLoadData.setBorder(javax.swing.BorderFactory.createTitledBorder("Load Data to Database"));

        jLabel2.setText("Input File:");

        jbInputFileButton.setText("Select ...");
        jbInputFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputFileButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Total registers uploaded:");

        totalRegisters.setEnabled(false);

        jLabel4.setText("Number of unique cities:");

        numberCities.setEnabled(false);

        jLabel5.setText("Number of unique states:");

        numberStates.setEnabled(false);

        jbRunSystem.setText("Run System Database Load");
        jbRunSystem.setEnabled(false);
        jbRunSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRunSystemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpLoadDataLayout = new javax.swing.GroupLayout(jpLoadData);
        jpLoadData.setLayout(jpLoadDataLayout);
        jpLoadDataLayout.setHorizontalGroup(
            jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoadDataLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbInputFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(numberStates, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(numberCities, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(totalRegisters, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoadDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbRunSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jpLoadDataLayout.setVerticalGroup(
            jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoadDataLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInputFileButton)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalRegisters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numberCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpLoadDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numberStates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jbRunSystem)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jtfNumberThree.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jtfNumberThree.setText("C");

        jtfNumberOne.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jtfNumberOne.setText("A");

        jpFindIsolationIndex.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Find Isolation Index")));

        jLabel14.setText("Highest Isolation:");

        highestIsolationIndex.setEnabled(false);

        jLabel15.setText("Lowest Isolation:");

        lowestIsolationIndex.setEnabled(false);

        jbFindIsolationIndex.setText("Start Finding Threads");
        jbFindIsolationIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFindIsolationIndexActionPerformed(evt);
            }
        });

        jLabel11.setText("Where:");

        jcbWhereToFind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brazil", "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA)", "Paraíba (PB)", "Paraná (PR)", "Pernambuco (PE)", "Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)" }));

        javax.swing.GroupLayout jpFindIsolationIndexLayout = new javax.swing.GroupLayout(jpFindIsolationIndex);
        jpFindIsolationIndex.setLayout(jpFindIsolationIndexLayout);
        jpFindIsolationIndexLayout.setHorizontalGroup(
            jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFindIsolationIndexLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(highestIsolationIndex, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addComponent(lowestIsolationIndex))
                .addGap(60, 60, 60)
                .addGroup(jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpFindIsolationIndexLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbWhereToFind, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbFindIsolationIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFindIsolationIndexLayout.setVerticalGroup(
            jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFindIsolationIndexLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(highestIsolationIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jcbWhereToFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpFindIsolationIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lowestIsolationIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFindIsolationIndex))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jtfNumberTwo1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jtfNumberTwo1.setText("B");

        jpXMLTransformer.setBorder(javax.swing.BorderFactory.createTitledBorder("XML Transformer"));

        jLabel16.setText("File output name:");

        jbExport.setText("Export to XML");
        jbExport.setActionCommand("");
        jbExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpXMLTransformerLayout = new javax.swing.GroupLayout(jpXMLTransformer);
        jpXMLTransformer.setLayout(jpXMLTransformerLayout);
        jpXMLTransformerLayout.setHorizontalGroup(
            jpXMLTransformerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpXMLTransformerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xmlOutputFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpXMLTransformerLayout.setVerticalGroup(
            jpXMLTransformerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpXMLTransformerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpXMLTransformerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(xmlOutputFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExport))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jbExit.setText("Exit");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        jtfNumberFour.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jtfNumberFour.setText("D");

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMainLayout.createSequentialGroup()
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbExit))
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfNumberOne)
                            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfNumberFour)
                                .addComponent(jtfNumberThree)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpXMLTransformer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpMainLayout.createSequentialGroup()
                                .addComponent(jpDatabaseConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(jtfNumberTwo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpLoadData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpFindIsolationIndex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(55, 55, 55))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNumberOne)
                    .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jpDatabaseConnection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpLoadData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfNumberTwo1))
                .addGap(18, 18, 18)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addComponent(jpFindIsolationIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpXMLTransformer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addComponent(jtfNumberThree)
                        .addGap(105, 105, 105)
                        .addComponent(jtfNumberFour)))
                .addGap(18, 18, 18)
                .addComponent(jbExit)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * MÉTODO IMPLEMENTADO PARA VOCÊ ESSE MÉTODO IMPLEMENTA A AÇÃO DO BOTÃO
     * "SELECT..."
     */
    private void jbInputFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputFileButtonActionPerformed

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.CANCEL_OPTION) {
            return;
        }
        selectedFile = fileChooser.getSelectedFile();
        jbRunSystem.setEnabled(true);             // habilita o botão de execução da operação de inserção dos dados no banco de dados.

    }//GEN-LAST:event_jbInputFileButtonActionPerformed

    /**
     * IMPLEMENTA A AÇÃO DO BOTÃO "LOAD XML CONF"
     */
    private void jbLoadXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoadXMLActionPerformed

        final String CONFIG_FILE_NAME = "config.xml";

        // Insira aqui seu código para implementar a ação do botão "Load XML Conf".
        // Esse código deve extrair dados do arquivo indicado na contante acima utilizando XPath
        try {
            File xmlFile = new File("config.xml");

            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            DocumentBuilder dbuilder = dbf.newDocumentBuilder();
            Document doc = dbuilder.parse(xmlFile);

            doc.getDocumentElement().normalize();

            XPath xpath = XPathFactory.newInstance().newXPath();

            Node dbnode = (Node) xpath.compile("/config/database").evaluate(doc, XPathConstants.NODE);

            String host = dbnode.getAttributes().getNamedItem("host-name").getNodeValue();
            String portNumber = dbnode.getAttributes().getNamedItem("port").getNodeValue();
            String instanceName = dbnode.getAttributes().getNamedItem("instance").getNodeValue();
            String user = dbnode.getAttributes().getNamedItem("user").getNodeValue();
            String passwordValue = dbnode.getAttributes().getNamedItem("password").getNodeValue();

            hostName.setText(host);
            port.setText(portNumber);
            instance.setText(instanceName);
            username.setText(user);
            pass.setText(passwordValue);
            

        } catch (IOException | ParserConfigurationException | XPathExpressionException | DOMException | SAXException e) {
            
        }


    }//GEN-LAST:event_jbLoadXMLActionPerformed

    /**
     * IMPLEMENTA A AÇÃO DO BOTÃO "RUN SYSTEM DATABASE LOAD"
     */
    private void jbRunSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRunSystemActionPerformed

        final String CSV_FILE_NAME = selectedFile.getName(); // Essa variável contém o nome do arquivo selecionado 

        // Siga aqui seu código
        String hn = hostName.getText();
        int p = Integer.parseInt(port.getText());
        String dbName = instance.getText();
        String u = username.getText();
        String pss = pass.getText();

        DBManager db = new DBManager(hn, p, dbName, u, pss);
        db.store(CSV_FILE_NAME);


    }//GEN-LAST:event_jbRunSystemActionPerformed

    /**
     * IMPLEMENTA A AÇÃO DO BOTÃO "START FINDING THREADS"
     */
    private void jbFindIsolationIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFindIsolationIndexActionPerformed

        if (selectedFile == null) {
            JOptionPane.showMessageDialog(this, "Please, first select the CSV dataset", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        final String CSV_FILE_NAME = selectedFile.getName(); // Essa variável contém o nome do arquivo selecionado 
        final String WHERE_TO_FIND = jcbWhereToFind.getSelectedItem().toString(); // Essa variável contém o nome e a sigla do estado selecionado

        // Siga aqui seu código

    }//GEN-LAST:event_jbFindIsolationIndexActionPerformed


    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        int r = JOptionPane.showConfirmDialog(this, "Do you really want to exit?", "Exit", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbExitActionPerformed

    /**
     * IMPLEMENTA A AÇÃO DO BOTÃO "EXPORT TO XML"
     */
    private void jbExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExportActionPerformed

        final String CSV_FILE_NAME = selectedFile.getName();      // Essa variável contém o nome do arquivo selecionado
        final String XML_FILE_NAME = xmlOutputFileName.getText(); // Essa variável contém o nome do arquivo ao qual deve ser exportado o XML

        // Siga aqui seu código

    }//GEN-LAST:event_jbExportActionPerformed

    private void hostNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostNameActionPerformed

    private void portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextField highestIsolationIndex;
    private javax.swing.JTextField hostName;
    private javax.swing.JTextField instance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbExport;
    private javax.swing.JButton jbFindIsolationIndex;
    private javax.swing.JButton jbInputFileButton;
    private javax.swing.JButton jbLoadXML;
    private javax.swing.JButton jbRunSystem;
    private javax.swing.JComboBox<String> jcbWhereToFind;
    private javax.swing.JPanel jpDatabaseConnection;
    private javax.swing.JPanel jpFindIsolationIndex;
    private javax.swing.JPanel jpLoadData;
    private javax.swing.JPanel jpMain;
    private javax.swing.JPanel jpXMLTransformer;
    private javax.swing.JLabel jtfNumberFour;
    private javax.swing.JLabel jtfNumberOne;
    private javax.swing.JLabel jtfNumberThree;
    private javax.swing.JLabel jtfNumberTwo1;
    private javax.swing.JTextField lowestIsolationIndex;
    private javax.swing.JTextField numberCities;
    private javax.swing.JTextField numberStates;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField port;
    private javax.swing.JTextField totalRegisters;
    private javax.swing.JTextField username;
    private javax.swing.JTextField xmlOutputFileName;
    // End of variables declaration//GEN-END:variables

    private File selectedFile;

}
